# Generated by Django 5.0.1 on 2024-01-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_image',
            new_name='product_image',
        ),
    ]
